name: ESLint

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/wbr-interpret/**/*'
      - 'packages/wbr-editor/**/*'
  workflow_dispatch:

jobs:
  eslint-interpreter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: >
          npm install -f $GITHUB_WORKSPACE/. &&
          npm run lint

