name: Lint

on:
  push:
    branches: [ main ]

jobs:
  eslint-interpreter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: >
          npm install --production=false $GITHUB_WORKSPACE/. &&
          cd $GITHUB_WORKSPACE/packages/wbr-interpret/ &&
          ls &&
          npx eslint ./src/

