name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: >
          npm install --production=false $GITHUB_WORKSPACE/.
          cd $GITHUB_WORKSPACE/packages/wbr-interpret/ &&
          npx eslint ./src

