name: Build and run Jest Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/wbr-interpret/**/*'

jobs:
  interpret-run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: >
          npm install --production=false $GITHUB_WORKSPACE/. &&
          npm run --prefix $GITHUB_WORKSPACE/packages/wbr-interpret build
          npm run test

